$(function () {
    
    /* ARRAY */
    const quotes = [
        ['I want to be a fly on the wall. Unseen. Unnoticed. But then I’d have to stop lighting things on fire. That’s not going to happen.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Everyone blames the victim. And then the victim becomes the villain.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['She’s afraid of me. Afraid of my grief. Afraid it’s contagious. I am a reminder of mortality.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Oh, how I wish you were here, brother. What I wouldn’t give to show you the stars.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The new world would call me unbalanced. The ancients would call me possessed. And that’s what I feel, clawing at the bounds of my ravaged psyche.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Life is too short for judgment, and love is too rare to lose.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I thought it would be difficult to masquerade as a good man, but I’ve found it frighteningly simple.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I promised myself I’d only rid society of the criminals, not the idiots. Maybe I should reassess my reasoning.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['They look like they are happy. But I look like I am sane. We both know that’s not true.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['But gentlemen don’t f*ck and tell. Or kill and tell. Good thing for you, I’m no gentleman.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['A man alone is suspicious. A man with friends is excusable.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I take a deep breath to steady myself. I hate teaching. But it makes me money for whores. And I love whores.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Yes, Beethoven was brilliant. But he chose to write songs. He should have chosen something more interesting. Like murder. Music only reveals yourself. Murder reveals others.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Rape is something I can never understand and will never tolerate. I might take their lives, but I don’t take their souls.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You’ll leave hundreds of discarded women in your wake, dozens of gutter babies with no one to love and nowhere to live. Dozens of me. Ra knows this world can’t handle that.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Fate has a fearsome humor.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I cornered one of the Patrol and threatened his eldest son’s life. Still not satisfied with the threat. Wasn’t creative enough. I just said I would kill him. I didn’t specify how.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’m naked. I have only the skin on my back, and even that isn’t all there. I’m soaked in blood, streaked with sweat. Every inch of me is red.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Darling, if you care about me, then there’s something wrong with you. Loving me is like loving a chainsaw.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You’re not alone. We’re all broken. And we’re all there for each other. That’s what the Roofers are. A family for those who have none.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Life isn’t worth living without risking love, even if the sweetest pleasure spawns the deepest pain.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Ask someone about their day, and they’ll kiss your feet. Remember someone’s name, and they’ll buy you lunch. People are so desperate to be seen. But I’m desperate to be invisible.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Sobriety makes me irritable. People make me irritable. Okay, life, in general, makes me irritable.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Of course I cheated. I’m too smart to play fair.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Yes, because all of us quiet types have the same interests and goals. We all get together in annual powwows and silently praise the same gods to keep us invisible, to keep us stereotyped.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You don’t love someone once. Love isn’t something you lose. Once it’s born, it stays. Sometimes dormant. Sometimes hidden. But it’s always there.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I should send you away. I should chuck your body over the edge of the roof and never look back. But I always look back. I always look for you.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Hold us tight, and tell us it will be okay. We’re all babies inside. Yes, there are layers of years, but they only serve to cover the truth, not to corrupt it.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['With no release, my mind cannibalizes itself.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I cast a spell over people. My eyes are hypnotic. My body a drug. They’re addicted. You’d understand if you met me. Let’s hope, for your sake, you never do.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Loss has a way of dampening life.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Everyone deserves a chance, deserves sympathy. Even the monsters. Especially the monsters.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Corruption. The perennial business model.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Punishment is rarely the suffering we endure and almost always the suffering we watch others endure.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Any life worth living comes with a little risk, a little pain.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Make threats instead. Therapy doesn’t suit you.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Presume. See? There it is. Your breeding. Your culture. The way you use language like a lawyer. A good family. A good education. Vocabulary reveals who you are.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['They see your mask, and they want to believe it’s real. I see your mask, and I want to know what you’re hiding.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I shouldn’t say anything. Questions have a way of ricocheting, and Ra knows I don’t want to give any answers.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I suppose you could kill them all, but sooner or later, your murder habit is going to catch up with you.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Mercy has a way of retaliating.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['War doesn’t care who gets caught in the middle. War has no rules.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I kiss him. First tender, then hungry. Crush my lips against him with all the questions unanswered and all the paths untaken.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['It ends how it began.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I don’t answer prayers, sweetheart. I’m the reason you pray in the first place.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I live my life with no excuses and no regrets.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I think we’re beyond death threats. Don’t make promises you can’t deliver.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I think that’s where hope lies. Not in the wait for something new, but in the change of something old.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Most people find it difficult to think outside the box, whereas we spend most of our time outside the box looking in.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Never underestimate a mage when it comes to lighting things on fire or blowing sh*t up.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I can never be that for her, but I can be her shadow. Always there. Always waiting. I’ll join the darkness so she doesn’t have to.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['It’s a stupid idea, but stupid is all we have left.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['All my time is spent in memory.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['It’s easier for them to accept physical injuries than mental illness, than substance abuse, than grief. What a pathetic, backwards society on a broken, upside-down world.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Let’s play a game.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['People are as replaceable as hats.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['It’s the apocalypse, but we’re still here, huddled on top of an upside-down world, waiting for the end, not realizing we’re in the epilogue.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Take care of the people, and the people take care of you. Or they’ll at least look the other way when the bodies start piling up, which inevitably happens around me.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The gods aren’t done till tragedy becomes ordinary, till catastrophe becomes routine, till man becomes apathetic. … Even war can be comfortable. Even war can be excused.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Another round of bombs. They unnerve everyone but me. I like fire. Explosions. Death. It’s a comfort. A truth we all share.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Greed reduces all men to adolescence.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['No excuses. No regrets. That’s what the Roofers taught me. Don’t be afraid to live. Don’t be afraid to die.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Mourners make great minions.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Darkness swirls around her. … The darkness of eternity. Of hope spelled in the stars. … A promise we are not alone. A promise we are part of something greater.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['A man with morals is a rarity at the end of the world.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’m living for dozens. I don’t get to choose who I am, where I go, what I do. I must be more than myself. I must live a life worthy of their memories.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['He breathes my name like the curse my mother thought me. I hope her ghost knows I lived up to her expectation.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Deathbed rationale amuses me.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Lies can be lethal, if you know how to wield them.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['That’s why I hate love. Love limits. Love judges. Love holds you to a higher standard. It’s a psychopath’s worst nightmare.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Get up, Julian. Move. No rest for the weary, the wicked, or the insane, and you’re all three.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Don’t kill the person; kill the source. Kill the poverty and the abuse and the neglect, but let the person live. Give the person a chance to change.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We don’t choose our birth.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You cannot save her from the world, Apolli. But perhaps you can make her strong enough to survive it.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['This isn’t a story about redemption; it’s a story about retribution.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We all bleed the same.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Live now, while you can. Love now, while you can.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You don’t choose who you love.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I hold you to a higher standard than curiosity.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We all die in the end.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['For once, I’d love if someone reacted unpredictably to death. Chant or somersault or fucking yodel to show me you have a mind of your own.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['She’s dressed in a white her soul doesn’t reflect, a drop-dead beauty with drop-dead morals.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Discontent is the source of my success.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['To passersby, she’d look like just another drunk, but she’ll be just another corpse if she keeps crossing that line.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I used to look approachable, but people took advantage of me.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Terms of endearment become terms of enslavement when used correctly.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Truth is raw but never ugly.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I thought we were past this, Apolli. Overprotective doesn’t look good on you. Go back to scowling at everything that moves.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Keep telling the truth, and you’ll forget how to lie.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Never apologize for being alive.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Show me the boy who rose from nothing to become boss of the Apolli. Show me the king who built an empire from thin air. Show me the most powerful mage in this Nyx-forsaken world. Show me the soul who struggles every fucking second for sanity but still manages to rise above everyone else. And show me how much that man loves me, if he loves me at all.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Demons don’t leave survivors.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We turn on each other instead of turning toward the sky.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You’re nothing without your power. If you weren’t born on the solstice, no one would want you. No one would need you. No one would give a shit about their helpless Apolli.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We can’t escape our upbringing. We can’t escape the echoes of blood.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I am no longer her pawn; I am the entire bloody chessboard.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I know some people call you a monster, but more people call you a god.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We all come home together.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The war is a series of divine feuds. The gods play puppets with people. There is always someone more powerful pulling the strings.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I relive her death before I remember her life.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Lying is what I’ve always done best. Besides murder. And drugs. And sex. Well, shit, I can’t help that I’m well rounded.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We wrestle grief like it’s a monster with claws when it’s really a ghost in the night.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I never wanted revenge, Apolli, but apparently, revenge is more important than I am.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You were my reason to live. Let me be yours.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I owe you my life, Sira Rune. Many times over. I won’t forget that. And I won’t waste it, either.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Honesty tears me open in emotional autopsy.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I never wanted to help, save, or protect people. I only wanted to light things on fire, blow shit up, and cut people open to see what’s inside.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['People are simple creatures. Feed them, fuck them, and put a roof over their heads.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['This isn’t revenge anymore. This is a revolution.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I never wanted their praise. Their respect, yes, but not their praise. Respect comes with fear. Praise comes with responsibility.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Murder steals lives. Rape steals souls. I’d rather be dead and whole than alive and empty.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Long live the Apolli.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’m about to break one of my rules.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Tell me his lies, and I’ll erase them with truth.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Bring it all down, love. Let it all burn.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Death follows you, Rune, because you deserve it.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Life rushes when we’re weak and drags when we’re ready, always at odds with what we need and when.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Logic bends to anyone’s will.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Men like us escape any cage.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Life’s too short to hide who you are.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Our people will follow you, Rune, if you let them.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Hate is easy. Love is hard. Because love makes us vulnerable.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Everyone serves a purpose, and that purpose is usually me.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['It’s not a gang. It’s an empire.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Save the future by stealing the past.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Coin is a marvelous lock pick.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We’re all monsters to someone.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Vengeance is a cycle that knows no end.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We are the people we surround ourselves with.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Forsake morals once; forsake morals forever.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The problem with revolution is that it never seems to end.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’m believing in you, Rune, because you’re too stubborn to believe in yourself.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Grant me fame for struggle, not fate.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Pain has comforted me through everything, from crib to criminal.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Comfort begets weakness. Struggle begets strength.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['They kill how nature intended—with their bare hands, survival of the fittest. It’s easy to separate your conscience with a knife or a gun or a bomb. But to close your hands around a man’s throat, to squeeze the panic from his still-beating heart, to wither his pulse and bewilder his eyes, to force him into the ultimate surrender—that is what I ask of my crew. That is what it takes to be an Apolli.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The Apolli will do what is necessary so you can do what is right.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Better a fool deluded than a sage depressed.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['When you live forever, you outlast secrets.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['To call him intimidating is to call me cruel. We are both so much more.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We saw each other at our worst and helped each other become our best.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We can never escape fate. Destiny spares no man.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Life always mocks our expectations of limits.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I rule how I live, by the seat of my pants and the skin of my teeth.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Comedy erases concern. That’s the reason for entertainment. To distract.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['There’s truth in every belief.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Erase it all. Burn it all. Bring it all down.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I wanted us to share forever.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I prefer the honesty of children to the masks of adults.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Fate is fickle as the gods.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I am no longer the same person. I lived a dozen lives since then.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Go away, Mother. You died a long time ago, by your own hand. Leave me alone, if not in peace.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Every coin is a corpse. Someone who crossed the Apolli. Bled dry in body then bank account.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Morality flees in the wake of desperation.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['He’s not dead. He can’t die. Because I’m still alive.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Arguing with you is as pointless as jacking off a eunuch.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I hate souvenirs. If it doesn’t cut, explode, or light things on fire, I have no interest in a fucking memento.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['She searches my face for answers she won’t find.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’m damned by fate or circumstance, depending on which brew of bullshit you believe.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Take solace in mortality. Those of us who live forever often forget to live.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The hottest fires forge the sharpest blades.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I must escape as I’ve done everything in my life, through murder and mutilation…and sometimes masturbation.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Most focus on what is, not on what could be.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['She gazes into my eyes as if she can read my constellations.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You take care of everyone else. Let me take care of you.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I chugged through life, blinded by routine, clutching an anchor that drowned me from feeling, from being, from living.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['This is what matters. Human connection. The hope at the heart of a storm. We all know the cliché, but we don’t understand till it’s our name on the obituary.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Everything with her is a song. Everything with me is a shout.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Seize the day before the day seizes you. Wise words from the mouth of a fool.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['War is always the answer to chaos, and we always balance on the edge of the breach.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['People don’t want to understand. We want to be understood. Cared for like infants. Possessed by comfort. Swaddled in lies and soothed with distraction. Give us chances we don’t deserve, and forgive our violence beyond redemption.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['It’s dark. Sightless and soundless. Without sensation. The absolute void of the truth we all fear. That there is nothing after death. That we are, as we always have been, nothing.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We are all people in the end. We all die in the end.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['She saved your life so you could live.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I am the reader, not the book.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Little born of blood harbors hope.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['It’s like jumping off a cliff. This is the adrenaline rush before the ground kills you with truth. You do not have wings. You are not free.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We fear death most of all. Mortality drives us mad. Morality, too.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’ll light a turd on fire if it’ll rescue me from this place, from myself.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Open your mind. The worlds are stranger than even you could imagine.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Suffering is caused, not chosen. Choice is seldom given, and chance too often imposed.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['No one succeeds without failure. No one moves mountains by standing still. You think you have all the answers, but you don’t ask any questions.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You fight everything, and that is why you survive nothing.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’ve seen beauty in pain and ugliness in pleasure.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’ll take their pity till I earn their fear.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Pain is an incentive for those numbed by eternity, but pleasure is a greater one.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Happiness is not conditional. Don’t be happy when. Be happy despite. Life is never perfect. Something is always wrong. But don’t let the wrong erase all the right.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Anonymity makes monsters of us all.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['May the Eye of the Brave watch over you always.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Grief is a shadow to show me the light.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Love offers more protection than any weapon.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We’re in the light at tunnel’s end, but it blinds us from the future.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You are what you are, Julian, and your echo will be as dark as your life.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['One of these games, you’re going to lose.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I was self-loathing and self-abusive—I hurt myself before and more than anyone could hurt me.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I fell for them both. Hard. My balance shifted, my focus faded, and the ground tilted beneath my feet. An avalanche led toward them, no matter how high I climbed.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Each word is quieter than the last. Each sentence reaches back through time.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['For most, handwriting reveals character. For me, the pen is a weapon in my arsenal, the ink a splatter of personalities I rotate between. Each blot is a Rorschach test only I can see. I am not one character; I am an ensemble.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Karma dissects my mind and rewires my soul.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['He wanted a toy, but he got a monster. If he doesn’t fear me today, he’ll fear me tomorrow.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I lived a hundred lives, saw a hundred more, experienced humanity in every form, in every fear.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['That’s what the Roofers taught me. Don’t be afraid to live. Don’t be afraid to die.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Mortality is a gift—a fire under our asses to feel, to experience, to live. But as with all gifts, there is a catch, and the catch is the end, and the end is the gift.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Weak stomach, weak spirit.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We are not different, though you will deny it, of course. I am the key, and you are the door, but you are too scared to step inside.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We aren’t meant to live forever, but we are meant to die free.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I don’t count myself among these monsters. I am my own breed of beast.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['As long as we are loved, we are never truly gone.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The universe is a strange, crazy, beautiful place. I doubt any answer is as simple as nothing.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Your ripples will be felt long after you’re gone, your memory strung through time for generations to come. Everyone will remember you, and no one will ever forget your name.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['There is no pleasure without pain. No love without loss. No joy without grief. No day without night. Light and dark exist as one, a symbiosis of necessity.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['When ghosts become memories and memories become ghosts, I am finally enough.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['How we love is the surest measure of how we live.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['There is a bond between you and Rune unlike any other.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Even in the end, hope is stubborn. A cry in the dark. A scream in the void. Unheard, unseen, unnoticed, but there. Always there.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Ghosts disappear, but legends never fade.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Is that why we tell stories? To save those we lost?', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I don’t trust people who help me without threat or reward.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The phoenix never sleeps. Infinity never dies.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We’re balanced. Soulmates. Two halves of the same spirit.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Time passes quick when you’re up and slow when you’re down.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The luxury of youth was never given to me. I was born a man, bred a monster, and bloomed like a weed to eclipse the sun.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I ache to be needed, to be wanted, because of my negligent mother. I know, I know. Get over it, Julian. But childhood is a critical period where seeds are set for the shitty plant metaphor we all become.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Life’s better when you laugh at yourself and kill others.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Paradise is a temptation. A snake, not an apple.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['War is stubborn as hope.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Memory immortalizes all ghosts.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Kyder spins so many webs, casts so many nets. Conversation with him usually leads to a trap, and agreement usually leads to a coffin.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Baize thinks I want his forgiveness, for us to be “buddies.” But friends make me rashy, and I’d trade likability for respectability any day of the week.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Happiness has a habit of erasing decency. That’s why I do my best to practice misery.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Don’t get sappy on me, Apolli. I rely on you for a steady stream of violence and debauchery.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['He thinks himself a monster, a villain, as I’m sure he insists to you. But I see, as I’ve always seen, his truth in the gray. His balance in the middle. The bad he does for good reasons.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Aim higher. Do something bigger. Something better. Don’t end up like me.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I neither deserve nor trust joy. It’s the breath before the storm. The gas before the explosion. I’ve lit too many fires to escape life unburned.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['There’s a beauty in destruction, an echo of the universe, of how we all began.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Grief did not make me numb; grief made me aware. Life is short. Once we are gone, we are gone forever, so yes, I live free, and I live hard.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Rebirth doesn’t erase the crimes of revenge.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Sacrifices for success are sins just the same.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Let me salvage this broken night with a thread of Maman’s wisdom. Forgiveness. Redemption. Second chances. I won’t become the monster that necessity requires.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Thank Ra she can’t sense my rage, or she would have left long ago. Not that she would have left for long. My ex-employees always return, albeit with a different arrangement of body parts.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’m bored again. Restless again. And restless leads to reckless.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I hate reminders of my childhood, but they always float to the surface like corpses in a lake.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’ll do what is necessary, so she can do what is right.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Logic bends to anyone’s will. Reason is a whore. Debate is futile. The truth is in the gray.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['People search for meaning in every ingrown toenail.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['My memory is as foolproof as my mercy is flawed.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Oh, sweetheart, if you think sex will stop this train wreck, then you are accurate in your research, but mistaken in your conclusion.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We all have the power to rewrite ourselves, especially you.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Torture is an art with one color of paint.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['It’s how I built the Apolli, gained Zawad’s loyalty, and overthrew the AP. Displays of power. Demonstrations of strength. Instill fear, then offer salvation, aka slavery.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Souls switch as spirits collide.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Suck it up, or you’ll fuck it up.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['If anyone out there gives a damn about this upside-down world on the distant shore of a wandering galaxy, then let me live to hold him again.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['If we’re going to die, I want to die with you.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Demons don’t leave survivors.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The threat of death is the spark of life. That’s what the wise think. You don’t want to know what I think.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['All truths in time. Let me fix that. All revenge in time.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I am the monster at the edge of the breach.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['This is necessary. This is right. This is the only way.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Nature and nurture conspire against me.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['This war ends now.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['How long must I prove myself? How many more must I kill? Sorry. Old habits die hard.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I sigh. He’s a curious one. You know what they say about curiosity. It killed the cat and everyone else. Wait, that’s me.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['A sacrifice. The last of many. The first of more. Die so others may live in peace.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Sweet release. Beautiful surrender. I promised you violence, did I not?', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We are the monsters at the edge of the breach. Damned by echoes of blood. Lost in the Eye of the Brave. Haunted by the elegy of the void.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I hate healers, though I frequently need them. They’re damned by decency, condemned to help. And heroism always boomerangs as miscarriages of glory.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['He hates me. He needs me. He wants to kill me. And that is how I built an empire.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['They have shared history, if that means anything. Most of the time, it doesn’t. It’s only an excuse to avoid the brutal reality that no one cares about you.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['He’s awkward and young and bony and short. All suit my reptilian desires. Easy to compliment. Easy to control.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['This is why I despise nostalgia. Even if you came from shit, that shit smells like home, like comfort, like something I crave. Fucking psychology. Even I’m its bloody slave.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I help others so they can help me. Tell me you care. Tell me I’m special. That’s why we’re all here.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Validate yourself. Don’t let others define your success.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I hate healers. Empathy irks me. There’s always a reason behind it, or rather, a request.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Face the truth, or drown beneath it.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['That’s the problem with ambition. People are too eager to sell their souls before they know the price.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['No one should suffer sober.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We so often push at walls in search of doors, and those that open when we need them most scar even the toughest hides.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Everything is soundproof. Good for trade. Better for business. Best for politics.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Entertainment diverts from the cogs beneath the stage.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['That’s what I’m supposed to say. Even if something costs me everything, gods forbid I show the true price of struggle.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Blood and sex forge the closest friendships. What? Not yours? I’m not surprised. You limit yourself in so many ways.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['No one resigns from the Apolli. The Apolli resign them.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You know what they say. Bold today, gone tomorrow.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Kindness, even feigned, has an enormous return on investment.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['In place of answers, rumors spread like a rash, mutate like a virus, till no one is immune to ignorance.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Rules are for the young or weak.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['People pretend they’re not greedy, lustful, savage creatures, but I’ve yet to find a problem that money, whores, or drugs can’t solve.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Pressure and pain compound and expand till all I am is what I lost.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['His smile strengthens, his tell of fear. We’re too much alike. The stronger the mask, the weaker the core.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['This is how our story ends. Once more opposites, magnets, strangers to each other and to ourselves.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I am a weapon. Nothing more. Everything less.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Aren’t we a beautiful disaster?', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['That’s the watered-down slogan I feed the kids. Easy to remember, to repeat, to market. They squawk it like parrots, because they’re too young to taste bullshit.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['She’s the kind of beauty that stops traffic and starts wars.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['But if I don’t risk everything, nothing will ever change.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I rise ever higher as I fall ever lower.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['How far would you go to save the one you love?', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Look how far Rune made you fall. You understand no love but your own.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Let it fall. Let it fade. Let it all burn down.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’ll let him ramble. People only listen when their minds are empty.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['What have you done to earn such a high horse? Sat on your ass and moved your eyes to read? But you judge me for getting shit done. Even if you don’t agree, you can’t deny my efficiency.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['My karma has blue balls from my unbalanced shadows. Light never comes in reward.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Welcome to the end. Wait, I shouldn’t miss a marketing opportunity. Welcome to the edge of the breach. There we go.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Better a fool than a fraud.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I see, but I cannot do—that is my blessing and my curse.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['There is a bond between you three unlike any other. Ties of the solstice. Links of fate.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Nothing works on the first try. That’s why you must fail and fail and fail again and again and again before you can fail again and maybe succeed. Or fail some more. Because you can’t manufacture progress.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['By all means, vote on our demise while I actually do something about it. You may not agree with my actions, but at least I get results.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Do whatever normal people do to show affection. It’s all nauseating to me. I’d trade a hug for a punch any day. A hug is a mixed signal. A punch is clear. I hate ambiguous bullshit.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['They all line up, and they all fall down.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’m not here to judge; I’m here to exploit.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Mysteries within mysteries. Buried alive by secrets. Suffocated by masks and crushed by costumes. But now, everything’s coming up corpses.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The world will change without you, boy.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['If you don’t know where I’ve been, you won’t understand where I’m going.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['For the love of Nyx, can’t anyone be a proper introvert these days? At this rate, I’ll need to escape to Jupiter for quiet. Too bad we’re more focused on retweets than rockets.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’ve hollowed out, replaced passion with practicality. I’m the empty shell that plagued my earliest nightmares.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['When I do sleep, my dreams are adult dreams. Not in the sexy way, but in the realistic way. No flying or magic or impossibilities. Only short, sensible responsibilities. I used to move worlds in my dreams, but now, I buy groceries. It’s depressing.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Some things never change, but most things must.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I fall—no, plummet—as everything I buried rises to tempt me, mock me, tear off my facades and reveal my raw, vulnerable core.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['By gaining what I always wanted, I’m losing what I took for granted.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['This is a shadow we share, a gift we suffer from the same lost ghosts.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’ve built and defused bombs since I was a troubled, creepy child—rest in peace, school gym and cafeteria. Defusing is easier than building, though. It’s easier to destroy than to create.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['See? We’re working together and singing along. Next thing you know, this will become a bloody musical. The bloody part, at least.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Fake a panic; save the day; gain their trust. Psychopathy 101.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Stop searching for answers to undeserving questions. Humans die too easy and quick to warrant unnecessary speculation.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I will come for you, as I came for so many others, and we will follow in their wake as the last waves of the storm.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['My feathers and facade burn to ash till I return to myself, forged in a volcano’s heart, stronger than a thousand suns.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Someone, somewhere, somewhen, needs your story. So go write it.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Maybe you’re not what you want to be. Maybe you’re something better.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We don’t mention the worsening episodes, the ticking bomb, the inevitability of my fate, whatever that fate may be. The clock continues, with or without my consent.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Necessity makes saints of us all.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Don’t blame me. The world forged this monster.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We perpetuate our own nightmares.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['My lies fall away like rain in a river.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Change comes, whether we want it or not. Same as truth.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We both want to start fires, watch worlds burn, and salvage our futures from the wreckage of our pasts.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Her ghosts follow her everywhere. They choose her actions as my demons choose mine. We’re puppets on the strings of grief and guilt. No, not only guilt for me. The whole choir of insanity pulls my chains.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['If I do one good deed in my life, let it be for you.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['My gang was a symbol of fear, then a symbol of hope. Now, it’s a symbol of salvation.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You were like a brother to me. I knew you a moment, yet I knew you forever.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You don’t have time. You make time. Carve out seconds between schedules. Whittle pockets of routine. Learn while you drive. Sing while you shower. Write while you shit. A paragraph each bathroom break makes a page a day makes a book a year. So what the fuck are you waiting for? GO OUT THERE, AND DO IT.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Wherever we go, we go together.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We cling to a candy facade in a desperate, pathetic attempt at comfort to fill the void each year of life deepens. Time hollows us out till we’re no more than a brittle shell of what-could-have-beens.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Be decisive. Be an inspiration. Take fate by the balls. Live large, or die trying.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Perhaps we all become each other in the end, melted together with our shared experience, our shared burden.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['When some doors close, they close forever.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’m used to edges, not curves. Breaches, not blessings. There’s no place for me in happily ever after.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We get what we ask for in the end, but we always ask for the wrong fucking shit.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['What’s that saying? Necessity is the mother of invention? More like the mother of survival. Because if there’s anything I can do, it’s what is necessary, and if there’s anything I know, it’s how to survive. Told you it’d come full circle.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Fucking gods, my life has been one long string of burned bridges and dumpster fires.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Darkness burns bright, if you wait long enough.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Ela took me in when no one else would. She showed me that home is built and family is found.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Duty thwarts dreams, time and again.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Endings are paradoxes; happy endings are oxymorons. Ra agrees. That’s why he vivisects my mind with the scalpel of his hatred. I agree, too. That’s why I let him.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You were sweet when it was easier to be sour, strong when it was easier to be weak.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['The right way to live is the way that feels right. You lived life on your own terms, and you died with an open heart.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Your death was meaningless, but your life was not.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['What was a brand of shame is now a badge of pride. If I survived you, I can survive anything.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['He’s horrifying. Or he would be, if I wasn’t accustomed to monsters. As it is, I’ve grown rather fond of my own.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’m sorry for the darkness you were handed, but I can’t excuse the darkness you released.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I raised myself. Built myself. Became myself. What I am from this moment forward is what I forged in the fathomless depths of struggle and suffering—of strength.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['I’ve always been a survivor, fashioning scraps into swords.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Whatever happens next, I’ll find you again.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['She smiles her mischievous smile, the smile that unraveled me at hello and ruins me at goodbye.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Experience shapes perception, so change your experience. Break all stigmas. Forgive when you want to forget. Redeem when you want revenge. Find strength through struggle. If you can’t break cycles, change them.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Be human. Be raw. Be graphic. Be bold. Be brave. Be unapologetically you. Your truth will set you free.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['You’re not alone. You’re never trapped. There’s always a door if you have the courage to open it.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Don’t get all sappy on me now, Julian. I like you tall, dark, and condescending.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Everything is a mirror. A circle. A cycle. A season for every struggle. The endlessness of suffering.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['Too soon, one more becomes one last becomes never again.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        ['We always find a way back to each other.', 'Rift Cycle', 'https://mybook.to/RiftCycle'],
        
        ['The sky is alive with a million whispers.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['I’m a walking death sentence for all who help me, a consequence for kindness.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['You’re beautiful, not broken. Different, not damaged.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['I’ve never stayed long enough on solid ground to learn how to stand without storm.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['I will give you more than vengeance; I will give you victory.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Use a weapon too soon, and it backfires. Use a weapon too late, and it burns out.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['They sent us here to die, but we survived, and to thrive, we must push harder, reach farther, and fight our fingers to the bones to become knives in Earth’s twisted heart.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Their death wish upon a star for me is all that keeps me standing.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['I thought you were better than an eye for an eye. Doesn’t matter. The world’s already blind.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Life is a long goodbye.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Each today is better than yesterday, and tomorrow leads me free.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Today, you’re right. I’ll let you go. But there will come a time when I can’t, and you can’t, and the sides we’ve chosen become the swords we die on.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Shut me down, and I’ll grow wings.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Use the darkest hour to summon the brightest dawn.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Wherever I stand along humanity’s spectrum, I am still a stripe of rainbow.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['She’s the shadow, and I’m the sun, and together we show each other direction.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['I use words they want me to speak in ways they want me to speak them. But all masks have cracks, mimicry reveals the stage, and borrowed phrases must be returned.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Don’t save what we are. Save what we could be. And we could be so much more than what we are.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['You don’t need to be fixed. You need to be seen.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Everything is an ocean, fading as sand in a midnight tide, structured to leave, spontaneous as storms. Time is a rainbow, with every moment an infinity.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['This storm will not drown me, because I am a force of nature, too.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['I am a butterfly at the brink of forever.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Family is choice, not chance. Bond, not blood.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Open your eyes. Let me in. Let me tell you words I didn’t have before but found just for you.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Hope doesn’t die. Hope is reborn.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['The universe is in her smile.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Together, we’ll rise higher than we ever fell.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Let wind steal my words, and let time erase my triumphs. Let seas drown my success, and let fires burn my failure. What use is a stranger’s memory if I’m forgotten by yours?', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['I don’t care if I die nameless, but I cannot die alone.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Nothing matters if I don’t matter to you.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Your name is my name. Your heart is my heart. Your soul is my soul. You won’t die forgotten, and you won’t die alone.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['I love you all infinity. I love you impossibility. I love you immortality. I love you magic and music, beauty and glory. I love you deathbed wishes and childhood dreams.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['Surrender becomes forever as our tongues dance in silent promises. And when it’s over, when it’s done, when hair sticks to flushed faces and chests heave with glittering skin, she smiles my smile, and I smile hers.', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        ['“You are my heartbeat,” I whisper. Koa beams. “And you are my dream.”', 'The Heartbeat of a Million Dreams', 'https://haloscot.substack.com'],
        
        ['The dead don’t fear.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['I’m no poster child, so I’m labeled the problem child, ushered into shadows while some palatable kid with the same socioeconomic crutches but a better attitude takes center stage.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Naked glitter parties fix all problems, just saying.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Kindness goes a long way. No one wants to work with a twat. Or a dick. Or a prick. Or any fucking genital.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['The older I get, the fewer fucks I give. Hoard those fucks. Don’t let anyone take them away.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['I hope you find a new love, a better love. I hope you let me go.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Death makes saints of us all.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['I offered you the world, but the world wasn’t good enough. You made your bed, and you shit in mine.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['I killed a boy, and I liked it.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Good people should win, even if bad people fight their battles.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['It’s ambition, not fraud. Innovation, not forgery. If others don’t grab fate by the swollen testicles and twist till the universe cries for its mommy, that’s their own damn fault.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['You catch more flies with honey than vinegar. But rotten corpses catch the most.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['You didn’t find love; love found you.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Hatred is a powerful ally.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Is an attempted hug like attempted murder? It should be. People should pay for unsolicited joy.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['I turn toward the problem. But it’s not only a problem, a snag, a hitch, a skip-in-the-step drawback. This is a “they found the tie-dye dick pics” and “call in those shady cousins” fuck-up.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['She’s one of those face-slap, gut-punch, universal beacons that makes me believe in a higher pattern, if not a higher power.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Batshit crazy runs in the family, but I’m the only murder whore.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Love heals the deepest wounds, and grief carves the worst.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['This is a poisoned apple, but I can’t stop humping the tree.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Fate cut her thread before she could find its root.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['It’s not the end of the world yet, Emma. Try something new before it is.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Nobody looks like what they are. I look normal, and that’s a worse lie than a political campaign.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Don’t encourage my imagination. Creativity is a greedy beast, and my impostor syndrome has claws.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['My death is your birth. My ending is your beginning. My exodus is your genesis.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Some people are worth fighting for. Find someone who is.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Don’t wait for the storm to pass. Become the storm.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Once you bypass morality, the heart pumps so much stronger.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['It’s not how we live but why we live that matters.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Georgina didn’t curse darkness anymore. She needed both shadows and stars to show her the way home.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Bloodlust is the mother of invention.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Money cancels all consciences. You’d never do that in a million years, till a million dollars cancel those years, then you’d do it today.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Everything I do, I do for them. Everyone I kill, I kill for them. If my greatest sin in life is loving my kids too much, then I can die in peace.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Time just is, and we move through it, around it, over it, under it…we are always dead and alive and unborn and stardust, all at once, all the time.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Somewhere, somewhen, there’s a version of you and a version of me, young and in love, perched on a rooftop, praying to a sunset, living forever in a photograph.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['It was beautiful when it was beautiful, and it was ugly when it was ugly, and it’s over, Sandy. It’s over, and you must let go.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Every step forward is another step free.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Don’t look so scared. You’re the one who bites.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Most pretty things are ugly at the end.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['You don’t mourn the end, Bob. You mourn the beginning. You mourn the spark, the rush of attraction, the addiction of hope, and the danger of dreams.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['If I can wish one thing into the living world, I wish you let me go.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Honesty is the best policy, Bob…unless it’s company policy.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Please don’t use big words while I’m bleeding.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['What we do and how we act in our darkest hour matters most. It’s easy to smile in sunshine, but it’s hard to smile in storm, and I’ve always laughed in the rain.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Love isn’t patient or kind. No, love is fierce. Love is a weapon. Love is a warrior. Love is an army that storms castles, a fleet that crosses oceans, the force at the heart of every battle cry.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Change is a beast we must tame to survive. Alex survived. Then again, he was a beast, too.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['Kids should see the big, bad, scary world and know they can fight, not hide. Sometimes you need a sword, not a shield.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['There are monsters in the dark, but those monsters are you. Become the beast you fear.', 'I Will Kill You', 'https://mybook.to/IWKY'],
        ['If it takes a sinner to make a saint, why punish the sinner?', 'I Will Kill You', 'https://mybook.to/IWKY'],
        
        ['Earth is not lost. It’s worse. It’s forgotten.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['I don’t care if you agree, but one day, even if you don’t believe what I believe, I hope you will believe in me.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['They’re wicked ordinary, corporate, and careful, climbing a ladder that never moves. I want to learn how to fly upside down.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['That was the price of freedom, for freedom always carries a fee. ‘Give us your trash, and we shall make treasure,’ they said atop skulls of infants and thieves.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['I have that look in my eyes, same as she did—the frantic, wild, hazel fear of one who has seen hell and asked for seconds.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Silence swallows lies. We retreat through vents, tunnels, esophagi, and memories till space is synthetic and time is acrylic, and no footstep forward nor turning back can shake the double vision of fate and mistakes.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Memories flake like petals in the wind, burned to crisps in conquest’s wake, villages in ruins, roses trampled by corpses. Mirrors make fools of us all.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['If you won’t find truth, truth will find you. When it does, it will be neither gentle nor kind, and you will regret the day you laughed at destiny.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Some things are better left buried.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['I won’t be the reason you fall.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['I hate joy. There’s no substance, no longevity. Better to wallow in misery’s predictable infinity than crest the sea only to forget how to swim.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Even if our stake in the ground is a sword in a neck, we swear loyalty to the comfort of familiarity’s throne.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['What we do today counts more than yesterday, so today, I change.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['No rebellions in heaven. No revolutions, either.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['The past is clingy, a needy spouse, intent on reunion or destruction, in marriage or divorce of destiny’s vow.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Dreams aren’t soft, tender pups wrapped in blankets against the cold. No, dreams are hungry, feral wolves who take the cold as a challenge. They walk through ice, because they know ice ends. Blizzards stop. Winter doesn’t last forever. There is a refuge, even if you can’t see it through the storm.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['I’d rather fall together than rise alone.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['We are in deep space, where rules don’t apply, where laws of physics turn toward each other and laugh, then cackle, then spit in our eyes.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Life is always the excuse for not living.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Time breaks all vows.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['This is the Ward. Save your lawsuits for lawful places.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['She was a force. Not always a good one, but a strong one.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Grief is an odd curse. You never feel what you think you’re supposed to feel—it’s either too much or too little. If I cry too much, she’d want me to be happy. If I cry too little, she’d think I didn’t care.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Breathe suffering into story. Find the starving parts of your soul, the slivers that ache for words, and lend those shadows voice.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Fortune never smiles twice.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['The worlds need your words. The stars need your stories.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Nothing works out how we want, but everything works out for the best.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Though I built a beautiful tomorrow, yesterday came crashing down.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['Some books burn.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        ['I’d like to travel, to see strange worlds and live strange lives, full of strange tomorrows. And I’d like to live this life…with you.', 'The Mortality Experiment', 'https://mybook.to/TheMortalityExperiment'],
        
        ['In new worlds, old ways must die.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['A princess who pleads has little power. A woman who asks has little control.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Everything is only what we pretend it to be.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Sin looks different on everyone.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Honor is a whore’s prayer, and glory is a virgin’s dream.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Most people are weapons, regardless of magic.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['You may choose your battles wisely, but you can never choose your war.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['The people who love you most won’t let you give up on yourself.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['We’re from different worlds with different chains. Then again, all cages feel the same.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['You will hurt people by doing the right thing, but you will hurt more by doing the easy thing.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['We are not always the sum of our parts. Many times, we grow beyond our blood. Sometimes, we grow wings.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Don’t let others underestimate you so much that you underestimate yourself.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['You’re mourning a future you thought guaranteed.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Dreams are wild, feral things. Even bleeding, they fight on, fight free.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Sometimes, the stars need us to become someone we’re not. Sometimes, we must change. Sometimes, we must fly. Sometimes, we must become strong enough to lift those who cannot lift themselves.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Death is full of stars.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Life is short, and death is long. You’re home now. You’re free. Burn the sun, and find your peace.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['And then, in the end, in the cold fist of fate, the light of a thousand suns will spark across time.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Rise up, and we all grow wings.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Our souls are an empire, and this is our legacy.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Let the future remember our wings. Let history remember our fangs.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Fear is our friend. Pain is our heritage. If fear and pain walk beside us, then we are walking in the right direction.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['If you do not stand, they will stand on top of you. If you do not speak, they will speak over you.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Silence is surrender.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['We don’t fall in love. In love, we rise.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['How we act in darkness determines whether we deserve the light.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Story is a place for all lost and lonely souls to escape, to relate, to find each other in darkness under stars.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Still waters run deep, but history remembers fires.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Life has no manners. It does not apologize for itself, so I must apologize for it.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Hope is a wild, stubborn, powerful thing. Hope will not go quietly, and hope will never burn out.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Live on, live free, in a feral forest, surrounded by fireflies. Soar among living lightning, with dancing stars in the breathing night. Break your back to build your wings, then fly on, and then fly free.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Drown in dreams of glory.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['You are the pit hell forged from heaven’s fall. The shadows carved by dying stars. The ghost of a people who once sang, who once danced, reduced to ash, an ember in the dust.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Death does not ask questions, so I do not, either.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Our story will survive, and memory is a victory far greater than life.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['May the stars bless the shadows, and may the sun bleed the night.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['This is what death does. It kills us before it takes us. Breaks us before it destroys us. Powders us to dust, then sweeps us off the map.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        ['Pain is proof we can survive.', 'Burn the Sun', 'https://mybook.to/BurnTheSun'],
        
        ['Do not be afraid to choose the wild path.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Strength means forging flaws into armor.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Disaster was exciting when it wasn’t your own.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['The woman didn’t need a name. She was different, and different was a scar. People always remembered scars.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['If someone needs to kill me, I’d like that someone to be you.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Isobel fell apart so many times that time itself ignored her.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Dust does not forgive.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Isobel has no magic, but she has control, and that is magic enough.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['There are only so many times history can repeat itself till there is nothing left to repeat.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Disaster had a way of eating dreams.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Escape was lucky, and luck was extinct. Freedom was fortune, and fortune always died. They’d built a broken world on stilts and rafts, then wondered why it sank.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['A story was worth more than a life. Lives ended. Stories never died.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['She painted this blush. Emotions were her palette. They were hers to borrow, not own.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Stop trying to save the world. The world doesn’t need saving; it needs healing.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['She was a workhorse, nothing more. An asset to utilize then euthanize.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Strength does not always lie in power, and power does not always lie in strength.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Murder was a fever dream, and she never wanted to wake.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['The runt turned cruel, because cruelty was power when you had none.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['You think you’re on top of the world now, but one day, the world will fall on top of you, and I won’t be there to save you.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Manners were temporary. Madness was eternal.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['They are always wrong about Isobel.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Her mind is a rotten, infected lump, but her heart beats strong with the pulse of dangerous dreams.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Broken things don’t always want fixing.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Power is not a thing to earn; it is a thing to conquer.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['We are all born into different worlds, and you survived your world the only way you could.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        ['Power is not a thing to earn; it is a thing to conquer.', 'Girl of Dust and Smoke', 'https://mybook.to/GDS'],
        
    ];
    
    
    /* RANDOM REC */
    function randomRec() {
        var rQ = Math.floor(Math.random() * quotes.length);
        $('#quote').html('<p>&ldquo;' + quotes[rQ][0] + '&rdquo;<br /><small><a target="_blank" href="' + quotes[rQ][2] + '">&ndash;&nbsp;' + quotes[rQ][1] + '&nbsp;<i class="fa-solid fa-square-arrow-up-right"></i> <span class="hide-SEO">(opens in new tab)</span></a></small></p>');
    }
    randomRec();

    $('#quote_btn').on('click', function(e) {
        e.preventDefault();
        randomRec()
    });
});